<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Doctors Listing</title>

    <?php require "./components/call-nano.php" ?>
    <?php require "./components/scroll-to-top.php" ?>
    <style>
        .pill {
            padding: 8px 24px;
            border-radius: 9999px;
            font-size: 14px;
            font-weight: 500;
            border: 1px solid #d1d5db;
            background: #ffffff;
            color: #374151;
            transition: all 0.2s ease;
        }

        .pill:hover {
            border-color: #ef4444;
        }

        .pill.active {
            background: #ef4444;
            color: #ffffff;
            border-color: #ef4444;
        }

        .pill-red {
            background: #ef4444;
            color: #ffffff;
            border-color: #ef4444;
        }

        .pill-red:hover {
            background: #dc2626;
        }

        .specialty-option {
            padding: 8px 20px;
            cursor: pointer;
        }

        .specialty-option:hover {
            background: #fee2e2;
        }
    </style>
</head>

<body class="bg-white">
    <?php require "./header.php" ?>
    <!-- FILTER BAR -->
    <div class="max-w-[1200px] mx-auto px-4 mt-10">
        <div class="flex items-center justify-between gap-4 flex-wrap mb-10">

            <!-- LOCATION PILLS -->
            <div class="flex items-center gap-3 flex-wrap">
                <button class="location-filter pill active" data-location="All">All</button>
                <button class="location-filter pill" data-location="Both">Both Locations</button>
                <button class="location-filter pill" data-location="Uttarahalli">Uttarahalli</button>
                <button class="location-filter pill" data-location="Hulimavu">Hulimavu</button>
            </div>

            <!-- SPECIALTY DROPDOWN -->
            <div class="relative">
                <button id="specialtyBtn"
                    class="pill pill-red flex items-center gap-2"
                    type="button">
                    <span id="specialtyLabel">All Specialty</span>
                    <svg class="w-4 h-4 transition-transform" fill="none"
                        stroke="currentColor" stroke-width="2"
                        viewBox="0 0 24 24">
                        <path d="M6 9l6 6 6-6" />
                    </svg>
                </button>

                <div id="specialtyDropdown"
                    class="absolute right-0 mt-2 w-56 bg-white border rounded-xl shadow-xl hidden z-50 max-h-96 overflow-y-auto">
                    <ul class="text-sm text-gray-700 py-2">
                        <li class="specialty-option" data-value="All">All Specialty</li>
                        <li class="specialty-option" data-value="Orthopaedics">Orthopaedics</li>
                        <li class="specialty-option" data-value="Cardiology">Cardiology</li>
                        <li class="specialty-option" data-value="Neurology">Neurology</li>
                        <li class="specialty-option" data-value="Vascular">Vascular Care</li>
                        <li class="specialty-option" data-value="Radiology">Radiology</li>
                        <li class="specialty-option" data-value="Laboratory">Laboratory Medicine</li>
                        <li class="specialty-option" data-value="Reconstructive">Reconstructive Surgery</li>
                        <li class="specialty-option" data-value="Oncology">Cancer Care</li>
                        <li class="specialty-option" data-value="Paediatrics">Child Care</li>
                        <li class="specialty-option" data-value="Pulmonology">Lung Care</li>
                        <li class="specialty-option" data-value="Gynaecology">Women Care</li>
                        <li class="specialty-option" data-value="General Medicine">General Medicine</li>
                        <li class="specialty-option" data-value="Psychiatry">Mind Care</li>
                        <li class="specialty-option" data-value="ENT">ENT</li>
                        <li class="specialty-option" data-value="Dermatology">Skin Care</li>
                        <li class="specialty-option" data-value="Urology">Urology</li>
                        <li class="specialty-option" data-value="Ophthalmology">Eye Care</li>
                        <li class="specialty-option" data-value="General Surgery">General Surgery</li>
                        <li class="specialty-option" data-value="Rheumatology">Rheumatology</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>

    <!-- CARDS SECTION -->
    <section class="w-full py-20">
        <div class="max-w-[1200px] mx-auto px-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-10 gap-y-32" id="doctorsGrid">
            <!-- Cards will be generated by JavaScript -->
        </div>

        <!-- PAGINATION -->
        <div id="pagination" class="flex justify-center items-center gap-2 mt-16"></div>
    </section>

    <script>
        const doctorsData = [
            // BOTH LOCATIONS
            {
                name: "Dr Mohan M R",
                kmc: "63479",
                qualification: "MBBS, MS, DNB - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics and Reconstructive Surgeon",
                location: "Both",
                image: "./assets/doctors/doctor-mohan.png",
                url: "./dr-mohan.php"
            },
            {
                name: "Dr Belehallli Pavan",
                kmc: "77282",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Both",
                image: "./assets/doctors/dr-behhehalli-pavan.webp",
                url: "./dr-belehallli-pavan.php"
            },
            {
                name: "Dr Keshava Murthy D",
                kmc: "95216",
                qualification: "MBBS, MS - Paediatrics",
                specialty: "Orthopaedics",
                role: "Specialist in Complex Trauma and Paediatric Orthopaedic",
                location: "Both",
                image: "./assets/doctors/dr-keshava-murthy.webp",
                url: "./dr-keshava-murthy.php"
            },
            {
                name: "Dr Prashanth S Gorur",
                kmc: "61480",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Fellowship in Arthroscopy & Sport Injuries & Shoulder Surgery",
                location: "Both",
                image: "./assets/doctors/Dr  Prashanth S Gorur - Ortho.png",
                url: "./dr-prashant-s-gorur.php"
            },
            {
                name: "Dr Suhas Raj S",
                kmc: "64485",
                qualification: "MBBS, DM - Cardiology",
                specialty: "Cardiology",
                role: "Consultant Cardiologist",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Manish Pai",
                kmc: "64472",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Both",
                image: "./assets/doctors/Dr Manish Pai.webp"
            },
            {
                name: "Dr Muruli Krishna",
                kmc: "62401",
                qualification: "MBBS, MS - Vascular Surgery",
                specialty: "Vascular",
                role: "Consultant Vascular Surgeon",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Arun Kumar A",
                kmc: "107818",
                qualification: "MBBS, MS - Vascular Surgery",
                specialty: "Vascular",
                role: "Consultant Vascular Surgeon",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Sailendra",
                kmc: "67846",
                qualification: "MBBS, DNB - Radiology",
                specialty: "Radiology",
                role: "Consultant Radiologist",
                location: "Both",
                image: "./assets/doctors/dr-sailendra.webp",

            },
            {
                name: "Dr Kruthika Prasad",
                kmc: "82886",
                qualification: "MBBS, MD - Pathology",
                specialty: "Laboratory",
                role: "Consultant Pathologist",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Dhanalaxmi Aniyappanavar",
                kmc: "71181",
                qualification: "MBBS, MD - Microbiology",
                specialty: "Laboratory",
                role: "Consultant Microbiologist",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Sarada Patil",
                kmc: "66391",
                qualification: "MBBS, MD - Pathology",
                specialty: "Laboratory",
                role: "Consultant Pathologist",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Shama Mohan",
                kmc: "24578",
                qualification: "MBBS, MS - Plastic Surgery",
                specialty: "Reconstructive",
                role: "Reconstructive Surgeon",
                location: "Both",
                image: ""
            },
            {
                name: "Dr Niti Raizada",
                kmc: "92267",
                qualification: "MBBS, MD - Oncology",
                specialty: "Oncology",
                role: "Consultant Oncologist",
                location: "Both",
                image: ""
            },

            // UTTARAHALLI ONLY
            {
                name: "Dr K N Prajwal",
                kmc: "107822",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr K S Manjunath",
                kmc: "18986",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Viresh Murgodi",
                kmc: "90066",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Ajay N Naidu",
                kmc: "128998",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr A Ramalingaiah",
                kmc: "22719",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Sushmitha K",
                kmc: "119988",
                qualification: "MBBS, MD - Paediatrics",
                specialty: "Paediatrics",
                role: "Consultant Paediatrician",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Naveen Kumar",
                kmc: "137522",
                qualification: "MBBS, MD - Paediatrics",
                specialty: "Paediatrics",
                role: "Consultant Paediatrician",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Arjun S Kashyap",
                kmc: "89509",
                qualification: "MBBS, MD - Pulmonology",
                specialty: "Pulmonology",
                role: "Consultant Pulmonologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Vivek K U",
                kmc: "2015",
                qualification: "MBBS, MD - Pulmonology",
                specialty: "Pulmonology",
                role: "Consultant Pulmonologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Sanjana Kumar",
                kmc: "119400",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynaecologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Swathi Iyenger",
                kmc: "124040",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynaecologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Greeshma G",
                kmc: "123445",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynaecologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Harsha K J",
                kmc: "71827",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Vishwas H V",
                kmc: "76352",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Kalyani Dilip Karkare",
                kmc: "MAH20040000584KTK",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist and Epilepsy Specialist",
                location: "Uttarahalli",
                image: "./assets/doctors/Dr Kalyani Dilip Karkare.webp"
            },
            {
                name: "Dr Nayana R",
                kmc: "114248",
                qualification: "MBBS, MD - General Medicine",
                specialty: "General Medicine",
                role: "Consultant Physician",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Siddharth Gosavi",
                kmc: "114893",
                qualification: "MBBS, MD - General Medicine",
                specialty: "General Medicine",
                role: "Consultant Physician",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Anusha V G",
                kmc: "115609",
                qualification: "MBBS, MD - Psychiatry",
                specialty: "Psychiatry",
                role: "Consultant Psychiatrist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Vibha B",
                kmc: "122344",
                qualification: "MBBS, MS - ENT",
                specialty: "ENT",
                role: "Consultant ENT Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Ajitha Tavvala",
                kmc: "109989",
                qualification: "MBBS, MS - ENT",
                specialty: "ENT",
                role: "Consultant ENT Surgeon",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Vani Yepuri",
                kmc: "93598",
                qualification: "MBBS, MD - Dermatology",
                specialty: "Dermatology",
                role: "Consultant Dermatologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Sharath C T",
                kmc: "95039",
                qualification: "MBBS, MS - Urology",
                specialty: "Urology",
                role: "Consultant Urologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Sanjay R P",
                kmc: "49790",
                qualification: "MBBS, MS - Urology",
                specialty: "Urology",
                role: "Consultant Urologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Druva",
                kmc: "102020",
                qualification: "MBBS, MS - Urology",
                specialty: "Urology",
                role: "Consultant Urologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Chaithanya",
                kmc: "111944",
                qualification: "MBBS, MS - Urology",
                specialty: "Urology",
                role: "Consultant Urologist",
                location: "Uttarahalli",
                image: ""
            },
            {
                name: "Dr Praveen Chandra",
                kmc: "49917",
                qualification: "MBBS, MS - Ophthalmology",
                specialty: "Ophthalmology",
                role: "Consultant Ophthalmologist",
                location: "Uttarahalli",
                image: ""
            },

            // HULIMAVU ONLY
            {
                name: "Dr Kishan Rao K",
                kmc: "63912",
                qualification: "MBBS, DNB (Ortho), MS (Ortho), MNAMS, PBFHS",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Hulimavu",
                image: "./assets/doctors/Dr Kishan Rao K.webp"
            },
            {
                name: "Dr Manohar Babu",
                kmc: "61141",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Amith Shetty P",
                kmc: "86086",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Trauma and Joint Replacement Surgeon",
                location: "Hulimavu",
                image: "./assets/doctors/dr-amit-shetty.webp"
            },
            {
                name: "Dr Raghavendra D Rao",
                kmc: "61474",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Spine Surgeon",
                location: "Hulimavu",
                image: "./assets/doctors/dr-ragavendra-rao.webp"
            },
            {
                name: "Dr Sudhindra Dharmavaram",
                kmc: "80575",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Monika Verma",
                kmc: "114869",
                qualification: "MBBS, MS - Orthopaedics",
                specialty: "Orthopaedics",
                role: "Consultant Orthopaedics Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Rakhi Sircar",
                kmc: "70253",
                qualification: "MBBS, MS - Paediatrics",
                specialty: "Paediatrics",
                role: "Consultant Paediatrician",
                location: "Hulimavu",
                image: "./assets/doctors/Dr Rakhi Sircar.webp"
            },
            {
                name: "Dr Ramya K S",
                kmc: "88023",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynecologist, Obstetrician and Laproscopic Surgeon",
                location: "Hulimavu",
                image: "./assets/doctors/dr-ramya-ck.webp"
            },
            {
                name: "Dr Dhanyatha G S",
                kmc: "111332",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynaecologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Shruthi G Naik",
                kmc: "123144",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynaecologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Prabha Ramadorai",
                kmc: "101380",
                qualification: "MBBS, MS - Gynaecology",
                specialty: "Gynaecology",
                role: "Consultant Gynecologist, Obstetrician and Laproscopic Surgeon",
                location: "Hulimavu",
                image: "./assets/doctors/dr-prabha-ram.webp"
            },
            {
                name: "Dr Suresh C H",
                kmc: "88022",
                qualification: "MBBS, MD - General Medicine",
                specialty: "General Medicine",
                role: "Consultant Physician & Diabetologist",
                location: "Hulimavu",
                image: "./assets/doctors/Dr Suresh CH.png"
            },
            {
                name: "Dr Namitha Rao",
                kmc: "109990",
                qualification: "MBBS, MD - General Medicine",
                specialty: "General Medicine",
                role: "Consultant Physician",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Aparna Parvatikar",
                kmc: "111160",
                qualification: "MBBS, MD - General Medicine",
                specialty: "General Medicine",
                role: "Consultant Physician",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Pudukode Ramnath Krishnan",
                kmc: "35974",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Sachin",
                kmc: "77128",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Kishore R",
                kmc: "109264",
                qualification: "MBBS, DM - Neurology",
                specialty: "Neurology",
                role: "Consultant Neurologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Deepa",
                kmc: "70644",
                qualification: "MBBS, MD - Pulmonology",
                specialty: "Pulmonology",
                role: "Consultant Pulmonologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Amrutha H",
                kmc: "169880",
                qualification: "MBBS, MD - Pulmonology",
                specialty: "Pulmonology",
                role: "Consultant Pulmonologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Niranjan P",
                kmc: "72600",
                qualification: "MBBS, MS - General Surgery",
                specialty: "General Surgery",
                role: "Consultant General Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Gautham S L",
                kmc: "80405",
                qualification: "MBBS, MS - General Surgery",
                specialty: "General Surgery",
                role: "Consultant General Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Richa Mishra",
                kmc: "99874",
                qualification: "MBBS, MS - General Surgery",
                specialty: "General Surgery",
                role: "Consultant General Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Agnigundala Anusha",
                kmc: "*0002315",
                qualification: "MBBS, MS - General Surgery",
                specialty: "General Surgery",
                role: "Consultant General Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Manish Pangi",
                kmc: "63524",
                qualification: "MBBS, MS - Vascular Surgery",
                specialty: "Vascular",
                role: "Consultant Vascular Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Harshalatha",
                kmc: "102956",
                qualification: "MBBS, MS - ENT",
                specialty: "ENT",
                role: "Consultant ENT Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Hanumesh A",
                kmc: "132038",
                qualification: "MBBS, MS - ENT",
                specialty: "ENT",
                role: "Consultant ENT Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Spoorthi G Itigi",
                kmc: "105550",
                qualification: "MBBS, MS - ENT",
                specialty: "ENT",
                role: "Consultant ENT Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Ranjani Gunasheelan",
                kmc: "KMC0000503",
                qualification: "MBBS, MD - Dermatology",
                specialty: "Dermatology",
                role: "Consultant Dermatologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Nidhika Sorake",
                kmc: "122363",
                qualification: "MBBS, MD - Dermatology",
                specialty: "Dermatology",
                role: "Consultant Dermatologist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Neeraj",
                kmc: "100855",
                qualification: "MBBS, MD - Psychiatry",
                specialty: "Psychiatry",
                role: "Consultant Psychiatrist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Chandra Shekaran R",
                kmc: "A-22166",
                qualification: "MBBS, MD - Psychiatry",
                specialty: "Psychiatry",
                role: "Consultant Psychiatrist",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Nikitha",
                kmc: "44595A",
                qualification: "MBBS, MS - Plastic Surgery",
                specialty: "Reconstructive",
                role: "Reconstructive Surgeon",
                location: "Hulimavu",
                image: ""
            },
            {
                name: "Dr Srinivas C",
                kmc: "65685",
                qualification: "MBBS, MD - Rheumatology",
                specialty: "Rheumatology",
                role: "Consultant Rheumatologist",
                location: "Hulimavu",
                image: ""
            },
        ];

        const cardsPerPage = 9;
        let currentPage = 1;
        let currentLocation = "All";
        let currentSpecialty = "All";
        let filteredCards = [...doctorsData];

        const defaultImage = "./assets/doctors/doctor-default.webp";

        function createDoctorCard(doctor) {
            const imgSrc = doctor.image || defaultImage;
            return `
                <div class="doctor-card relative w-[300px] mx-auto" data-location="${doctor.location}" data-specialty="${doctor.specialty}">
                    <div class="absolute -top-28 left-1/2 -translate-x-1/2 z-20">
                        <img src="${imgSrc}" alt="${doctor.name}" class="w-52 h-52 object-cover rounded-full" onerror="this.src='${defaultImage}'" />
                    </div>
                    <div class="relative bg-white rounded-2xl border border-gray-200 shadow-sm text-center pt-28 overflow-hidden">
                        <button class="absolute top-4 right-4 text-gray-400 hover:text-red-500 transition">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                            </svg>
                        </button>
                        <div class="px-5 pb-6">
                            <h3 class="text-lg font-semibold text-gray-900">${doctor.name}</h3>
                            <p class="text-xs text-gray-400 mt-1">KMC: ${doctor.kmc}</p>
                            <p class="text-sm text-gray-500 mt-1">${doctor.qualification}</p>
                            <p class="text-sm text-red-500 font-medium mt-3 leading-snug">${doctor.role}</p>
                        </div>
                        <div class="flex border-t border-gray-200">
                            <a href="#" class="w-1/2 bg-red-500 text-white text-sm font-medium py-3 hover:bg-red-600">Book Appointment</a>
                            <a href=${doctor.url} class="w-1/2 text-red-500 text-sm font-medium py-3 hover:bg-red-50">View Profile</a>
                        </div>
                    </div>
                </div>
            `;
        }

        function applyFilters() {
            filteredCards = doctorsData.filter(doctor => {
                const locationMatch = currentLocation === "All" || doctor.location === currentLocation;
                const specialtyMatch = currentSpecialty === "All" || doctor.specialty === currentSpecialty;
                return locationMatch && specialtyMatch;
            });

            currentPage = 1;
            renderPage();
        }

        function renderPage() {
            const grid = document.getElementById("doctorsGrid");
            const start = (currentPage - 1) * cardsPerPage;
            const pageCards = filteredCards.slice(start, start + cardsPerPage);

            grid.innerHTML = pageCards.map(doctor => createDoctorCard(doctor)).join('');
            renderPagination();
        }

        function renderPagination() {
            const pagination = document.getElementById("pagination");
            pagination.innerHTML = "";
            const totalPages = Math.ceil(filteredCards.length / cardsPerPage);
            if (totalPages <= 1) return;

            for (let i = 1; i <= totalPages; i++) {
                const btn = document.createElement("button");
                btn.textContent = i;
                btn.className = `px-4 py-2 rounded-full transition ${i === currentPage ? "bg-red-500 text-white" : "bg-white border border-gray-200 hover:border-red-500"}`;
                btn.onclick = () => {
                    currentPage = i;
                    renderPage();
                    window.scrollTo({
                        top: 0,
                        behavior: "smooth"
                    });
                };
                pagination.appendChild(btn);
            }
        }

        // Location filter
        document.querySelectorAll(".location-filter").forEach(btn => {
            btn.onclick = () => {
                document.querySelectorAll(".location-filter").forEach(b => b.classList.remove("active"));
                btn.classList.add("active");
                currentLocation = btn.dataset.location;
                applyFilters();
            };
        });

        // Specialty dropdown
        const specialtyBtn = document.getElementById("specialtyBtn");
        const specialtyDropdown = document.getElementById("specialtyDropdown");
        const specialtyLabel = document.getElementById("specialtyLabel");

        specialtyBtn.onclick = () => specialtyDropdown.classList.toggle("hidden");

        document.querySelectorAll(".specialty-option").forEach(opt => {
            opt.onclick = () => {
                currentSpecialty = opt.dataset.value;
                specialtyLabel.textContent = opt.textContent;
                specialtyDropdown.classList.add("hidden");
                applyFilters();
            };
        });

        document.addEventListener("click", e => {
            if (!specialtyBtn.contains(e.target) && !specialtyDropdown.contains(e.target)) {
                specialtyDropdown.classList.add("hidden");
            }
        });

        // Initialize
        applyFilters()
    </script>

</body>

</html>